version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/autonomica-frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "jairodriguez"
    assignees:
      - "jairodriguez"
    labels:
      - "dependencies"
      - "npm"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Python dependencies in API
  - package-ecosystem: "pip"
    directory: "/autonomica-api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "jairodriguez"
    assignees:
      - "jairodriguez"
    labels:
      - "dependencies"
      - "python"
      - "api"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]
      - dependency-name: "uvicorn"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Python dependencies in Worker
  - package-ecosystem: "pip"
    directory: "/autonomica-worker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "jairodriguez"
    assignees:
      - "jairodriguez"
    labels:
      - "dependencies"
      - "python"
      - "worker"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "celery"
        update-types: ["version-update:semver-major"]
      - dependency-name: "redis"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Docker base images
  - package-ecosystem: "docker"
    directory: "/autonomica-worker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jairodriguez"
    assignees:
      - "jairodriguez"
    labels:
      - "dependencies"
      - "docker"
      - "security"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for base images
      - dependency-name: "python"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jairodriguez"
    assignees:
      - "jairodriguez"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for critical actions
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]
      - dependency-name: "actions/setup-node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "actions/setup-python"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Python dependencies in root
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jairodriguez"
    assignees:
      - "jairodriguez"
    labels:
      - "dependencies"
      - "python"
      - "root"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for pip-tools (if used)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "jairodriguez"
    assignees:
      - "jairodriguez"
    labels:
      - "dependencies"
      - "python"
      - "pip-tools"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    target-branch: "develop"
    ignore:
      - dependency-name: "pip"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Terraform (if used)
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jairodriguez"
    assignees:
      - "jairodriguez"
    labels:
      - "dependencies"
      - "terraform"
      - "infrastructure"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for GitHub CodeQL
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "jairodriguez"
    assignees:
      - "jairodriguez"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      - dependency-name: "github/codeql-action"
        update-types: ["version-update:semver-major"]